### ISSUE TITLE
Make iltorb an optional dependency

### ISSUE THREAD

**Issue by bartveneman** [projectwallace/css-analyzer#153]
Support for brotli is built-in for Node >= 10, so we need to check whether brotli support is active, and otherwise install iltorb.

**Comment by bartveneman** [comment]
Might also drop support for Node 8 and don't bother at all. That's probably easier.

**Comment by hacknug** [comment]
Node 8 is comming to EOL at the end of this month so you may just drop it and call it a day: https://nodejs.org/en/about/releases/

**Comment by bartveneman** [comment]
Native brotli support is > Node 11 https://nodejs.org/api/zlib.html#zlib_class_brotlioptions
