### ISSUE TITLE
Raw CSS analysis - Valid CSS being reported as invalid, won't generate stats

### ISSUE THREAD

**Issue by rheydt** [projectwallace/css-analyzer#162]
Replication steps:
- Go to projectwallace.com, log in, choose new import
- Use the "Paste raw CSS" option and paste in a valid chunk of CSS, e.g `h1 { color: #000000; }`
- Click the "analyze CSS" button

Expected outcome: 
- CSS stats are generated without errors

Actual outcome:
- "There is a problem with your CSS" error banner appears at the top of the page
- "Is your CSS valid?" message appears beneath raw CSS field
- No stats are generated, import does not work.

First noticed this yesterday, 1/8/2020. My last successful raw CSS import was 14 days ago, so it must have broken during that time span.

Obviously, this is a blocker for being able to generate stats using raw CSS. Let me know if you need more info. Tested on latest Chrome (v79) on Mac 10.14 using an account that has old successful imports and also using a brand new account with no imports.

**Comment by bartveneman** [comment]
Hey, I can't seem to reproduce this issue on projectwallace.com. I found some logs of CSS errors, but no reasons why. Would you mind hop into a Discord room to discuss the details? https://discord.gg/5egx2dK

**Comment by bartveneman** [comment]
This should be fixed now, thanks again for the detailed report.
