### ISSUE TITLE
Install fails (iltorb)

### ISSUE THREAD

**Issue by BreannW** [projectwallace/css-analyzer#168]
Hello. I'm receiving the following errors on install. Is there anything I can do to get this package working? 

Thanks! 

request GET https://github.com/nstepien/iltorb/releases/download/v2.4.5/iltorb-v2.4.5-node-v72-darwin-x64.tar.gz
WARN install self signed certificate in certificate chain
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: self signed certificate in certificate chain
gyp ERR! stack     at TLSSocket.onConnectSecure (_tls_wrap.js:1473:34)
gyp ERR! stack     at TLSSocket.emit (events.js:311:20)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:916:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:686:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/bre/Desktop/working/testProject/node_modules/iltorb
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN cleancss@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iltorb@2.4.5 install: `node ./scripts/install.js || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iltorb@2.4.5 install script.

**Comment by bartveneman** [comment]
iltorb is indeed troublesome, and I haven't got around a complete fix yet. The master branch is free of iltorb at the moment, but I haven't put a version number on that yet, because it's a (small) breaking change and I want to put some more changes in the next big version increment (see #129)

For now you could workaround the issue by `npm install @projectwallace/css-analyzer#master`.

**Comment by BreannW** [comment]
Thank you for your quick response! I just tried to run npm install @projectwallace/css-analyzer#master and recieved the following: 

`Could not install from "@projectwallace/css-analyzer#master" as it does not contain a package.json file.`

**Comment by bartveneman** [comment]
My bad, try tranging your package.json manually so it includes this:

```json
"dependencies": {
  "@projectwallace/css-analyzer": "projectwallace/css-analyzer#029d4a8f77f579d4086cfd213ae33289e7eade8f"
}
```

That will install css-analyzer at it's current state, without automatically upgrading any changes that I might do to master without notice.

**Comment by BreannW** [comment]
I was able to get it working! Thank you!

**Comment by camohub** [comment]
What about package.lock file. This updates lock file am I right? I would like to run npm require
