### ISSUE TITLE
Report origins of properties/values

### ISSUE THREAD

**Issue by bartveneman** [projectwallace/css-analyzer#189]
I had a discussion with a coworker today who said we had too many unique border-colors. We didn't initially notice, because CSS-Analyzer only tells us *which* colors we have. Where `orange` is a fine color for text, it may not be a proper `border-color`. 

Analysis could look like this:
```json
{
  "colors": [
    {
      "property": "border-color",
      "value": "green",
      "colors": ["green"],
      "selectors": [".test123 #i-know-right"]
    },
    {
      "property": "background",
      "value": "linear-gradient(#000, #fff)",
      "colors": ["#000", "#fff"],
      "selectors": [".test123 #i-know-right"]
    }
  ]
}
```

## Desired analyzer ouput

Add an additional `origins` property, that contains an array of CSSDeclarations where the color appeared. Adding CSSSelector would be optional, but nice.

```json
{
  "values.colors.unique": [
    {
      "count": 3,
      "value": "green",
      "origins": [
        {
          "property": "border-color",
          "value": "green",
          "count": 1,
          "selectors": [".test123 #i-know-right"]
        },
        {
          "property": "background",
          "value": "linear-gradient(green, #fff, green)",
          "count": 2,
          "selectors": [".test123 #i-know-right"]
        }
      ]
    }
  ]
}
```

**Comment by bartveneman** [comment]
Csstree has an option where we can get the string location of any node, so from v5 this will totally be possible.

**Comment by SalimBensiali** [comment]
Hi @bartveneman I would be keen to contribute & see this happen, as I was looking for a way to see a report of unique colors for background and foreground separately. Is there a v5 branch yet? What would be the next steps? Thanks

**Comment by bartveneman** [comment]
V5 is being developed in a private repo, so it's not possible to contribute yet. 
I'd like to understand your usecase a bit better, because knowing foreground and background colors seems a bit limited? There's borders, shadows, gradients, custom properties and they can all have colors, but also opacity, so I wonder what you're trying to achieve.

**Comment by SalimBensiali** [comment]
No worries. I am interested in statically flagging any potential colour contrast issues in an app. One way of going about this is to list out all background and foreground colors separately, then check and compute the contrast ratio for each and every background & foreground pair. So I would say If foreground and background are too broad as categories, maybe a grouping by actual property in source could be used instead. It would then be up to the user to do the background vs foreground categorisation.

**Comment by bartveneman** [comment]
I see. This could work for a limited set of conditions, so I'd be very careful when taking this approach. The cascade and other properties (like size/opacity/etc.) may influence the contrast ratio as well. In the end that's hard to determine with static analysis, but tools like https://polypane.app/ can definitely help with that.

**Comment by SalimBensiali** [comment]
Thanks @bartveneman and for the link to polypane. I will definitely check this out. Obviously my idea is not a replacement for rigorous color contract testing in actual browsers. I am interested in shorter feedback cycles for the obvious and potential contrast violations.

**Comment by bartveneman** [comment]
This feature (specifically for colors) is included in v5 and on projectwallace.com/analyze-css
