### ISSUE TITLE
compareSpecificity can't be imported

### ISSUE THREAD

**Issue by nicojuhari** [projectwallace/css-analyzer#323]
Hello

the 'selectors/utlis.js' are missing from dist folder

package: 5.9.0

![image](https://user-images.githubusercontent.com/55665352/233331517-c86edfca-29dc-40f8-a23a-64502f29554e.png)

thanks

**Comment by nicojuhari** [comment]
Hi @bartveneman 

is it an quick fix for this ?

thanks

**Comment by bartveneman** [comment]
Well, sponsorships aren't really big, so I still have a full-time day job to pay bills. Maybe later this week I'll have some time to take a look, but no promises.

**Comment by nicojuhari** [comment]
Hi @bartveneman 

sorry to bother you, but any updates on this ?

Also, I use the package in Angular project, maybe this could help you

Thank you

**Comment by bartveneman** [comment]
This is purely a typescript error on my side, right? I'm using the exact function in other (non-ts) projects without issues.

**Comment by bartveneman** [comment]
Fixed in https://github.com/projectwallace/css-analyzer/releases/tag/v5.10.1
